# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PagerSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PagerSample
	pod 'HMSegmentedControl'

  target 'PagerSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PagerSampleUITests' do
    # Pods for testing
  end

end
